// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwCoVHtMR3XuOnGqTz_0f-AZnUVEU_CuU',
    appId: '1:289459066309:web:ab5e2cefe8972185b767ac',
    messagingSenderId: '289459066309',
    projectId: 'cs310-project-4e016',
    authDomain: 'cs310-project-4e016.firebaseapp.com',
    storageBucket: 'cs310-project-4e016.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAUBUVvH7Q_MacZYD_QU2AOM3CrCEaGJY',
    appId: '1:289459066309:android:60e5842fdc0b7c49b767ac',
    messagingSenderId: '289459066309',
    projectId: 'cs310-project-4e016',
    storageBucket: 'cs310-project-4e016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBs9IFUJVfM_Be0E5GYhCe7fcT5Covly0',
    appId: '1:289459066309:ios:45b1b802f48ca600b767ac',
    messagingSenderId: '289459066309',
    projectId: 'cs310-project-4e016',
    storageBucket: 'cs310-project-4e016.firebasestorage.app',
    iosBundleId: 'com.example.cs3102026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBs9IFUJVfM_Be0E5GYhCe7fcT5Covly0',
    appId: '1:289459066309:ios:45b1b802f48ca600b767ac',
    messagingSenderId: '289459066309',
    projectId: 'cs310-project-4e016',
    storageBucket: 'cs310-project-4e016.firebasestorage.app',
    iosBundleId: 'com.example.cs3102026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwCoVHtMR3XuOnGqTz_0f-AZnUVEU_CuU',
    appId: '1:289459066309:web:8ba4e77fa4eb13eab767ac',
    messagingSenderId: '289459066309',
    projectId: 'cs310-project-4e016',
    authDomain: 'cs310-project-4e016.firebaseapp.com',
    storageBucket: 'cs310-project-4e016.firebasestorage.app',
  );

}