// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeJIJd8F0A3IUkT5GFZy1_cuMDIBZTJ0',
    appId: '1:385888874725:web:6faef45c1f944e895a240c',
    messagingSenderId: '385888874725',
    projectId: 'bandmate-8831d',
    authDomain: 'bandmate-8831d.firebaseapp.com',
    storageBucket: 'bandmate-8831d.firebasestorage.app',
    measurementId: 'G-1TBW9ZGPX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD81Ycg_CM4YxU6k-FZ1KIoGDaFeDkuP4Q',
    appId: '1:385888874725:android:e40f97d1899fecd05a240c',
    messagingSenderId: '385888874725',
    projectId: 'bandmate-8831d',
    storageBucket: 'bandmate-8831d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHeXp3TFcrUCr6hs-yxjwPcs9hv_hZFA',
    appId: '1:385888874725:ios:2f2c2840817bf5e15a240c',
    messagingSenderId: '385888874725',
    projectId: 'bandmate-8831d',
    storageBucket: 'bandmate-8831d.firebasestorage.app',
    iosBundleId: 'com.example.cs3102026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHeXp3TFcrUCr6hs-yxjwPcs9hv_hZFA',
    appId: '1:385888874725:ios:2f2c2840817bf5e15a240c',
    messagingSenderId: '385888874725',
    projectId: 'bandmate-8831d',
    storageBucket: 'bandmate-8831d.firebasestorage.app',
    iosBundleId: 'com.example.cs3102026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNeJIJd8F0A3IUkT5GFZy1_cuMDIBZTJ0',
    appId: '1:385888874725:web:32293e90b632b1845a240c',
    messagingSenderId: '385888874725',
    projectId: 'bandmate-8831d',
    authDomain: 'bandmate-8831d.firebaseapp.com',
    storageBucket: 'bandmate-8831d.firebasestorage.app',
    measurementId: 'G-48TD5YE9CS',
  );

}